### ISSUE TITLE
A Podcast?

### ISSUE THREAD

**Issue by deanhtid** [wesbos/ama#102]
Don't think this has been asked before...

Have you ever considered or any plans to do a podcast?

**Comment by wesbos** [comment]
Yesss - I even have a domain name and a logo ready to go. 

I'd love to do one, and hope to start it up sometime. Right now I'm pretty focused on making courses but I think a podcast would be a fun thing to add to the mix if I can figure out how to do it without taking up too much time.

Thanks for the Q!

**Comment by RosanaRufer** [comment]
Your wishes came true, @deanhtid :)

**Comment by deanhtid** [comment]
I know! Haha @totemika
