### ISSUE TITLE
How do you deal with healthcare, ugh...

### ISSUE THREAD

**Issue by jondaiello** [wesbos/ama#103]
How do you handle the cost of healthcare for you and your family? I used to be a freelancer but it got to the point where the cost was exorbitant. Just curious!

**Comment by wesbos** [comment]
I live in Canada where most of Healthcare is paid for by the government.  

My family is sick right now - 3 of us had to get medicine and the total was $9. The doctors visit was free. 

Some stuff isn't covered by the government and you have to pay for that out of pocket or get your own health insurance. I pay $300/month for my entire Family of 4 and that covers glasses, dental, partial massage, specialized therapists and other things like wheelchairs and whatnot. 

So yeah - I'm _very_ fortunate to live in Canada - it's a great environment to be an entrepreneur.  

🇨🇦🇨🇦🇨🇦

**Comment by wesbos** [comment]
I just found this on my phone - it's some of things that aren't free in Canada

![img_5477](https://cloud.githubusercontent.com/assets/176013/19940521/5a2e2052-a103-11e6-843f-ef1324edc830.JPG)

**Comment by jennschiffer** [comment]
lmao well at least in the states we get sick notes for "free"

**Comment by jondaiello** [comment]
Wow. That's pretty amazing. Thanks for that throughout response!
