### ISSUE TITLE
What is your stack?

### ISSUE THREAD

**Issue by alamgirqazi** [wesbos/ama#107]
As a full-stack developer, what is your "stack"?
 
I know it can change from project to project but what is your preferred one?

From Front-end to back-end to persistent, caching, devops etc?

**Comment by wesbos** [comment]
Good question - I've got two main stacks that I use to build websites / apps. 

Most of my applications that need something custom  - like my product websites - are built on this:

Node.js Backend
Mongodb database with Mongoose to interface with it. I usually host the DB on Mlab
Express.js Server
Async for flow control - though I'm slowly moving over to ES6 promises
Host my node apps on Digital Ocean with an Nginx server running on top of my node apps - though I've increasingly interested in Caddy server instead.

Some of my sites run CloudFlare which is really helpful. 

For content based sites - like my own where you have many "content types" (blog post, page, speaking engagement...) I use WordPress. I'm a huge fan of how easy it is to put together a custom interface on the WordPress backend with Custom fields/post types/taxonomies.  

This is exactly what WordPress was made for and I can be extremely productive in it. 

Hope that helps!
