### ISSUE TITLE
some Q's 

### ISSUE THREAD

**Issue by carronju008** [wesbos/ama#109]
hey, im doing a project for schpool and i deadly need you to answer these questions for me.
they are about you :D 
email me the answers plz at: justincarron03@gmail.com
•	How did this venture/business start?
•	How long has it been in the community?
•	Where is it located?
•	How many employees does the business currently have?
•	What consumer needs and/or wants does the business satisfy?
•	How has it affected the community? (i.e., involvement/support in the community, job creation, reputation, etc.)
•	Additional details about the business (Interesting facts, important milestones, other details…)
thank for in advance :D

**Comment by wesbos** [comment]
I emailed these answers - thanks!
