### ISSUE TITLE
React/Redux app talking to an API, and using devise authentication

### ISSUE THREAD

**Issue by natyv** [wesbos/ama#111]
I just bought your React for Beginners package, and its been quite helpful. The Learn Redux series is a fantastic bonus. I have a nice working app, but I'm trying to talk to an API to get the data, and really struggling to as where my dispatch function would go. Can you please point me to any resources I can refer to? I have looked at a few different tuts and ended up confused!

Thanks,
Nat

**Comment by natyv** [comment]
To be more specific, I want to dispatch the api call, after getting the param from the route.

**Comment by AntonNiklasson** [comment]
Not to intrude on the AMA, but this might help you: http://redux.js.org/docs/advanced/AsyncActions.html

**Comment by wesbos** [comment]
Thanks a lot - I hope to do a tut on this in the future though :)
