### ISSUE TITLE
What sublime packages are you using ?

### ISSUE THREAD

**Issue by asotog** [wesbos/ama#112]
Like to work with: jsx embedded (emmet autocomplete), es6, etc. Was checking your redux  tutorial which is great btw, noticed that you typed jsx inside js file and it gets autocompleted based on the component you are importing (es6), kind of emmet fashion

**Comment by wesbos** [comment]
That is emmet - you can use it in JSX → http://wesbos.com/emmet-react-jsx-sublime/
