### ISSUE TITLE
What chrome extensions are you using and which ones have proven invaluable to you?

### ISSUE THREAD

**Issue by Maximization** [wesbos/ama#115]

**Comment by wesbos** [comment]
* Video speed controller for speeding up any html5 video
* LastPass
* JSON Viewer
* Redux dev tools
* React Dev tools
* Falcon Proxy for watching TV shows cross border

**Comment by akashnimare** [comment]
@wesbos you should give a try to -
* [OneTab](https://chrome.google.com/webstore/detail/onetab/chphlpgkkbolifaimnlloiipkdnihall?hl=en)
* [The Great Suspender](https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg?hl=en)

**Comment by wesbos** [comment]
I'm not a tab monster - I always close them down when I don't need em!

**Comment by akashnimare** [comment]
@wesbos haha cool then. I open way too many tabs 😀
