### ISSUE TITLE
Partial migration from Durandal / Knockout to React

### ISSUE THREAD

**Issue by nwinger** [wesbos/ama#118]
Hi,

I'm part of a Typescript-project built on Durandal / Knockout. Currently the build process is done by a grunt task, that compiles the typescript.

I've been wondering for a while, how to partially implement react into this project when it comes to building and bundling. Just curious if you've had any similar experiences or any thought at all on the subject? 

By the way, thank you for your contributions to the JS-community!

**Comment by wesbos** [comment]
Thanks for the question! I haven't done anything like this before - pretty new to Typescript so I can't be too much help - sorry!
