### ISSUE TITLE
What other teachers do you recommend?

### ISSUE THREAD

**Issue by wesbaker** [wesbos/ama#120]
Do you know of any other teachers that put out materials like yourself for other languages and frameworks? I watch both @mpj's and your videos, but would like to see similar courses for other languages and frameworks like Ruby, Rails, Clojure, Elixir, Elm, etc.

**Comment by wesbos** [comment]
@mpj is the best - his stuff is great!

Pragmatic Studio has some of the best Ruby/Elm stuff https://pragmaticstudio.com

For everything else, I'm not sure. There are definitely good teachers in that space, I just don't really pay attention.

**Comment by josephbona** [comment]
I recommend @excid3 if you're looking into learning Rails. Chris offers a lot of free content so you can get a feel for his style. Very focused videos; I really like his style of teaching.

**Comment by jaydeepkarena** [comment]
https://www.labnol.org/internet/learn-web-development/31945/     here you will find many good teachers for many technologies
