### ISSUE TITLE
Setting up you development environment.

### ISSUE THREAD

**Issue by calebcordry** [wesbos/ama#123]
Could you talk a bit about the things you do to prepare a development environment for a new project? For example if you are starting to make a quick app for the Javascript30 course, are you setting up a webpack-dev-server for prototyping etc?

**Comment by wesbos** [comment]
I always get up and running as fast as possible. 

* For simple HTML+CSS+JS I'll use browser-sync (we do this in some JS30 vids) 
* For React I used create-react-app
* For my node or WordPress sites I mostly use Gulp to handle everything except the JavaScript bundling (webpack does that)

**Comment by wesbos** [comment]
(Hope that helps -feel free to ask more Qs below)

**Comment by calebcordry** [comment]
Thanks something like browser-sync is what I was looking for when I need something quick (I hadn't gotten to those videos yet). Also could you explain why your using Gulp & webpack for more complex apps, instead of just using webpack and some loaders?
