### ISSUE TITLE
What app do you use for designing your course websites?

### ISSUE THREAD

**Issue by amjith** [wesbos/ama#124]
Hi Wes,

Did you build your own sites for the course websites or do you use a pre-existing app? 

How about the videos? Do you use a hosted service or do you host them yourself? What video player do you use? 

How about user/login management?

**Comment by wesbos** [comment]
Goood question! I recorded a video just for you → https://www.youtube.com/watch?v=4CS436KZ35A

**Comment by amjith** [comment]
Thanks a lot for taking the time to answer the question in such detail. 

At the end of the video you mentioned that you wouldn't recommend someone to build their own platform, I'm curious if you have an alternate suggestion.

Is there a library you use for the video player?

**Comment by itzsaga** [comment]
@amjith I didn't get to watch the whole video but at the beginning he says something along the lines of, "this is just a regular video player". I would assume it's just utilizing the `<video>` tag in HTML5.
