### ISSUE TITLE
Best ExpressJS resource?

### ISSUE THREAD

**Issue by fleeco** [wesbos/ama#127]
Hey Wes!  Huge fan of all your stuff.  Do you have a favorite ExpressJS resource?  With babel / promises / etc sometimes the best practices can elude me.  If you made a course I'd pay handsomely for it! :P

**Comment by wesbos** [comment]
Let's just say you'll _love_ my next course :) ;)

**Comment by adibhanna** [comment]
@wesbos when will you release this course?

**Comment by wesbos** [comment]
In a few weeks - working on it as we speak!

**Comment by darrylnoakes** [comment]
Is this course available?

**Comment by darrylnoakes** [comment]
Is this course available?

**Comment by DarrylNoakes** [comment]
Is this course available?
