### ISSUE TITLE
Building An Audience For Your Courses

### ISSUE THREAD

**Issue by MarcL** [wesbos/ama#133]
Hi Wes,

Firstly, thanks for all you do for the dev community and for being a friendly guy on Twitter!

I meant to post a question a few weeks back but then I ended up listening to a few podcasts with you on (Developer Tea and Fullstack Radio) which answered some of them.

I've worked for 20+ years in the video games industry (C/C++) and then moved across to Node.js based apps for a big media company here in the UK. I'd like to create a short course in a similar vein to some of yours but I'm unsure what to make the course about and how to build an audience.

So my questions are:
- how did you go about choosing what courses would work for your audience (and sell well)?
- how did you initially start to build up your mailing list for your courses? Was it just the consistency of your tweets and blogging of relevant articles?
- how did you encourage people to buy your first course?
- do you use paid advertising to drive traffic to your courses? If so, is there a particular platform that you suggest. I think I've seen some of your ads on FB for your ES6 course. 😄 

Thanks,
Marc

**Comment by wesbos** [comment]
Hello! Thanks for the great questions.

**how did you go about choosing what courses would work for your audience (and sell well)?**

There isn't a whole lot that goes into choosing - it's generally whatever I know really well. If I can't stop talking about how awesome ____ is at solving a problem, it's probably something I'll create a course on. I intentionally don't pick obscure topics as I don't want to have to sell people on a technology. It should be pretty apparent  to visitors that a specific technology is popular so I just need to work on convincing them that they should spend some time learning it. If someone is a die-hard Angular dev, I don't waste cycles on trying to convert them to React - not worth it. 

I also don't pick topics that are changing too quickly. I'd love to do a course on Webpack, or Jest, or React Native, but right now those projects are moving too quickly and ifI were to spend 3 months on a course it would be out of date by the time I'm done recording. 

**how did you initially start to build up your mailing list for your courses? Was it just the consistency of your tweets and blogging of relevant articles?**

Initially it was a signup form on some Blog posts I have about Sublime Text. I took it down after I launched my Sublime Text book and now I don't have a single "Sign up!!!" form anywhere on my site. My emails come entirely from people who take my courses. 

**how did you encourage people to buy your first course?**
jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab jab right-hook.

I blogged and tweeted about Sublime for years (jab). Then I came out with a paid course and it was an easy decision for people to make. reciprocity is my business model

**do you use paid advertising to drive traffic to your courses? If so, is there a particular platform that you suggest. I think I've seen some of your ads on FB for your ES6 course. 😄**

I'm trying to figure this out right now but it's not really making any money. I've spent about 10k so far and I've made about 5-7k. I know I can crack facebook ads, it's just about figuring it out :)

**Comment by Roilan** [comment]
@MarcL since @wesbos didn't mention the context/book for jab jab jab right hook reference. I posted it below, it's an awesome read.

https://www.amazon.com/Jab-Right-Hook-Story-Social/dp/006227306X

**Comment by MarcL** [comment]
@wesbos - Thanks so much for taking the time to give a detailed answer. Time to up my jabbing. :boxing_glove: 

@Roilan - Thanks. I thought it was the Gary V book Wes was referencing but I've never read it. Time to add it to the list. 👍

**Comment by wesbos** [comment]
I've never read it either - I think you can get the gist of it from the title :)

**Comment by MarcL** [comment]
Yes, totally. Makes perfect sense. I just need to prioritise giving to others via blogging / tweeting I think. Cheers!
