### ISSUE TITLE
Which JS testing framework and template engine do you use?

### ISSUE THREAD

**Issue by growdigital** [wesbos/ama#134]
…and which would you recommend for a JS newbie?

I am a bit overwhelmed by all the choices!

**Comment by wesbos** [comment]
Good question - and I'm going to give you an answer than most newbies hate hearing - it doesn't really matter. 

For React, it was Expect, but now that seems to be moving over to Jest. 

For everything else it's been Mocha though I hear great things about all kinds of other testing frameworks. 

I've used cucumber in the past for integration tests, was a bit slow to work with and didn't leave me loving it. 

for template engines, either JSX with React, or Jade/Pug for everything else.

**Comment by growdigital** [comment]
> it doesn't really matter

Nooooooo! Only joking, that’s actually good to know. Many years ago I agonised over Macromedia FreeHand vs. Adobe Illustrator. I use Sketch now ;)

I’ll give Mocha a bash and I’m attracted by the vanilla-ness of Handlebars.

thank you :)

PS another answer which most newbies hate hearing (and favoured of @adactio) is 

> it depends…
