### ISSUE TITLE
Any chance we will see a course for building a backend / API?

### ISSUE THREAD

**Issue by bbroens** [wesbos/ama#138]
I'd love to see a quality course for setting up and writing a capable backend / API. Is this something you are planning to do? Maybe with node.js.

**Comment by wesbos** [comment]
Haha yes- it's almost as if you are looking over my shoulder! I'm just about to start recording my next series which I've been working on for the last 3 months. It's going to be building both a backend and part of an API with Node.js 👍

**Comment by sjordan1975** [comment]
I'm a student in many of your courses. Would love to see where this API course ended up? I imagine it as a sort of "less theory, more action, API done right".

**Comment by darrylnoakes** [comment]
Is this course available on your website?
I would really like to take it! :)

**Comment by darrylnoakes** [comment]
Sorry, looked at your courses list and found it :).
