### ISSUE TITLE
Can't add new issue to learn redux start files Repo

### ISSUE THREAD

**Issue by jasan-s** [wesbos/ama#139]
[https://github.com/wesbos/Learn-Redux-Starter-Files/issues/new](url) leads to 404. The issue I had was that running npm run build in the learn-redux directory outputs error:  `NODE_ENV is not a recognized as an internal or external command`

**Comment by wesbos** [comment]
Did you google that error? Check this link for an explanation → http://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman
