### ISSUE TITLE
Which course first?

### ISSUE THREAD

**Issue by lukeburford** [wesbos/ama#140]
Presuming I have a book or 2 of foundational JS under my belt, does it make sense to tackle JS30 or ES6 for Everyone first? (after that going for React, Learn Redux then the Node course). Have actually done a bit of React course but definitely need to get stronger fundamentals too :)

**Comment by wesbos** [comment]
Hey! 

There are a lot of people who start JS30 but decide to take ES6 first so they can become more comfortable with the syntax first. 

I'd say do at least the first half of ES6 before doing JS30. 

Hope that helps!

**Comment by spences10** [comment]
I have done it [arse-backwards](http://www.urbandictionary.com/define.php?term=arse-backwards) and did the first half of JS30 [which is awesome btw!] then decided to do ES6 for Everyone which I got half way through and now I'm nearly finished with React for Beginners.

I'm literally flitting between them all, then I'll be like:
![](https://media.giphy.com/media/zv9jdvSu5m1FK/giphy.gif)

**Comment by wesbos** [comment]
Haha glad to hear that - Learning isn't linear so it's hard to give someone a linear path.

**Comment by spences10** [comment]
@wesbos I know what you mean about projects getting difficult 80% of the way through, I need to push through all my half finished 'side projects'

Glad I found your AMA too 😀
