### ISSUE TITLE
How do you set up a new machine?

### ISSUE THREAD

**Issue by czeluff** [wesbos/ama#142]
Hi Wes,

Setting up a new machine can be pretty time consuming. I was curious if you have any scripts that download all of your plugins, apps, etc?

**Comment by wesbos** [comment]
It's funny but I don't. I've only had 2 macbooks since I bought my first one about 8-9 years ago and my only move used the migration assistant to move everything over. 

I'm thinking about starting fresh on my next one, but it's still runnin' smoothly!
