### ISSUE TITLE
Keyboard and Mic Setup

### ISSUE THREAD

**Issue by infn8** [wesbos/ama#146]
What is your setup so that you can live code and not hear any typing and clicking in the videos?

**Comment by wesbos** [comment]
Good question! 

I've detailed all my mic setup over here → http://wesbos.com/uses

When I started it was a big problem for me and it really all boils down to vibrations from my desk making it's way up to the mic. You can stop this by either getting a shock mount for your mic, or back in the early days I would just put a t-shirt under my keyboard which would dampen the sound.
