### ISSUE TITLE
Your nodejs build system?

### ISSUE THREAD

**Issue by divyanshu013** [wesbos/ama#151]
Hi @wesbos, I was wondering what kind of build tool/system/etc do you use in your backend?

I've been using webpack/babel for some time in the frontend (with react) and love it. However, most(if not all) of the ES6 features work out of the box in node (except `import` and `export` as I recall), so transpiling with babel doesn't seems like a good idea. Would love your take on this.

Also webpack bundles your modules together (great on frontend), but is it wise to bundle your modules on the backend? Since modules work well with node, is there any advantage in doing that? Besides this, if your frontend is using react, how do you go about managing your build (perhaps keeping both frontend and backend separate or building them together)?

Would appreciate any tips/suggestions/advice on this :)

**Comment by wesbos** [comment]
I'm with you on not transpiling Node - everything I want is already in Node (including Async + Await) so I don't see any benefit in transpiling just so I can use a different import syntax. 

The ES6 syntax for Node modules will be here in about a year, and I'm just waiting until then before I use it.

**Comment by divyanshu013** [comment]
Thanks for answering @wesbos! What's your take on using webpack for backend?

**Comment by wesbos** [comment]
I don't use it for anything backend currently - just for front end deps
