### ISSUE TITLE
Do you have pro photos?

### ISSUE THREAD

**Issue by spences10** [wesbos/ama#152]
Hey Wes,

Did you get a professional photographer to take all your profiles photos or are you one of these people that always look immaculate in any photo? 📸 🖼

**Comment by wesbos** [comment]
Haha - I def don't look good all the time :) 

My Github Photo is from my wife  - she's pretty good

My main photo from my website and twitter is from Pam Lau - shes a pro photog that takes all the photos over at HackerYou. It's about 3 years old now and I'm due for a new one...
