### ISSUE TITLE
Have you built your own accounting software?

### ISSUE THREAD

**Issue by spences10** [wesbos/ama#153]
I think I saw a tweet from you hinting that you have built your own bookkeeping software...

I'd love to know if you have as I want to build something similar but have no idea where to start

**Comment by wesbos** [comment]
I haven't - I actually use Freshbooks to do all my expenses and invoicing. The other big part of my income comes from course sales, so at the end of the year I need to get my accountant all the sales data and expenses. To do this cleanly I've written some reports that spit out to a CSV :)
