### ISSUE TITLE
When is your podcast coming out?

### ISSUE THREAD

**Issue by atuttle** [wesbos/ama#16]

**Comment by wesbos** [comment]
Great question - I've got the website, art and everything setup for it. I just need to record a few episodes (which I have a huge list).

So - I'm working to get my current video series on FlexBox and my Book, as well as a new part-time course for @HackerYou. 

I'd say I've got two months left on those, and then I'll turn my focus to the podcast.

Not as soon as many would like, but focusing on other projects right now is my priority!

**Comment by ssanj** [comment]
Looking forward to it! :+1:
