### ISSUE TITLE
To use a CSS framework or not?

### ISSUE THREAD

**Issue by jonmajorc** [wesbos/ama#160]
Hello Wes!

Do you find yourself running to a css framework out the gate on a new project, or do you like to build a home grown solution to your problems with bringing in some light weight tools? If you do most home grown solutions, can you elaborate what are the css tools you do run to when building a project?

Thanks!

**Comment by wesbos** [comment]
I usually opt not to go for a CSS framework unless I need to slap something together really quickly. Every large project I've done I've always regretted the CSS framework, esp the grid part.

For tools, I keep it simple. Sass or Stylus with BEM or Styled Components with React.
