### ISSUE TITLE
Can I clone the Learn-Node repo?

### ISSUE THREAD

**Issue by HarleyGolfGuy** [wesbos/ama#162]
Hi Wesbos,

I am going through the "Learn Node" course and I have a project I'm working on where it would be handy (for the project AND my learning) to re-use the layout and structure of the 'dang-that's-delicious' web app.  Is that OK or would I be violating any copyright laws or other laws? 

...and while I'm asking the question, I guess it could apply to ANY of the courses you offer...for example the React "Catch of the Day" app.

Thank you!

**Comment by wesbos** [comment]
Yep - absolutely! Do whatever you like. Just don't make another node course using the code :)

**Comment by HarleyGolfGuy** [comment]
haha!  :)
