### ISSUE TITLE
Tell me about the `Bos` family name

### ISSUE THREAD

**Issue by spences10** [wesbos/ama#164]
Hi @wesbos,

Have you done any research on your family name Bos?

Just a quick Google come up with [this](https://www.ancestry.co.uk/name-origin?surname=bos), are you of Dutch decent?

Is that why you pronounce `Schema` the way you do 😄

**Comment by wesbos** [comment]
I am dutch! Bos means Forest in Dutch.  I grew up in Canada though - my opa and oma are from Holland.

I pronounce `Schema` the correct way 🤣🤣🤣🤣

**Comment by spoxox** [comment]
Do you know Trudy and Pieter Bos?
