### ISSUE TITLE
Intro Music in #JS30

### ISSUE THREAD

**Issue by ogostos** [wesbos/ama#167]
Hi, Wes. 
Thanks for all your greatly fun and 'the way it should be' courses!

I have a question not related to coding, however I've found that I'm not the only one interested :)
What music do you use as an intro to your vanilla "Javascript 30 days" course? I mean those guitar riffs. The outro also seems to be from the same song, if I'm not mistaking. 

Thanks for your answer.

**Comment by wesbos** [comment]
It's the Divided -  for tonight we're strangers. I absolutely love this band. The vox are ft Karl Shubach - the vocalist of Misery Signals

https://www.youtube.com/watch?v=v9zFF5aBR84
