### ISSUE TITLE
New to JS, learning ES6, new job doesn't support it

### ISSUE THREAD

**Issue by invious** [wesbos/ama#174]
I just took a job with a company that doesn't use es6 -- and it's all I know so far. I come from python and ES5 is gross. What can I do?

**Comment by wesbos** [comment]
Write ES6 and compile to ES5. I know it's hard to sometimes convince some existing developers to change their workflow, but I'd start with having chats with them about changing that. 

I had this once where I just compiled locally with my own tooling and committed the compiled version - it's gross but sometimes you gotta get creative go get around bureaucracy
