### ISSUE TITLE
Lightweight date/time picker

### ISSUE THREAD

**Issue by AbleLincoln** [wesbos/ama#175]
Hey Wes!
Huge fan of your work. Syntax has become my new workout jam.
I'm making a form for a client and it needs to have date and time fields. The client wants to have a visual date/time picker like the one on [Air BnB](https://www.airbnb.com/) or similar sites. Do you have any recommendations for a how I should go about this? A library would be nice, but I don't want to have to add _more_ dependencies (I'm trying to avoid using Bootstrap or jQuery). But I'm not sure if it's worth creating on my own from scratch. Is there anything you use for similar scenarios?
Btw, this a Node app with Sass for preprocessing, but other than that I'm trying to keep it pretty dependency-light.

Thanks so much!

**Comment by sapegin** [comment]
If you ever change your mind about frameworks, this one is very good: http://react-day-picker.js.org/ ;-)

**Comment by wesbos** [comment]
I'd use the airBNB date picker if I was you. I haven't used too many in the past so I don't know a whole lot about this :)
