### ISSUE TITLE
[Learn-redux] Cannot read property 'likes' of undefined

### ISSUE THREAD

**Issue by yuripramos** [wesbos/ama#180]
I'm sorry but I've found only here ask questions about your free course.. 

I'm in the lesson 13 and when I try to dispatch the increment likes, I got this title error. It's a little bit weird for me mainly because the increment is working when I'm outside the single.js

Here's my single.js

```
import React from 'react';
import Photo from './Photo';

const Single = (props) =>{
  const i = props.posts.findIndex((post) => {
    return (
      post.code === props.params.postId
    )
  });
  const post = props.posts[i];
  console.log('single photo props', props);
  return (
    <div className="single-photo">
      <Photo i={i} post={post} {...props} />
    </div>
  )
};

export default Single;
```

**Comment by wesbos** [comment]
Hey - you'll have to post your Photo component too

**Comment by yuripramos** [comment]
Hi! I've solved the issue, I was forgetting to pass the id props that I've changed to keyId, that's why they got undefined.
