### ISSUE TITLE
Support for your courses

### ISSUE THREAD

**Issue by jerriep** [wesbos/ama#187]
How do you handle support for your courses? 

Surely you get many people contacting you with support questions which are not related specifically to the course content, and I cannot see that you can give this general kind of support. 

Where do you draw the line, and how do you communicate this to people who have purchased your courses?

**Comment by wesbos** [comment]
This is not something I've totally figured out - most of it happens in the Slack room where there are some amazing people who try help out. I'll jump in from time to time and help out as well, but it's definitely a little more than I can handle. 

Helping people with their problems really gives me an idea of where people struggle and I can craft the next course around common tripping points. 

The FAQ for each course helps a lot too - the problems are fairly similar in each case, so it's not like lots of new stuff comes up.

I do get lots of email too, I'll try help out but almost always it's followed up by a "Oh NM I got it!" an hour or so later. 

For stuff that isn't directly related to the course, I'll often chime in on my thoughts, or pull some code from a project I've done - I like to help if I can!

I'd like to hire someone to help with support at some point too, so if anyone knows someone :)
