### ISSUE TITLE
How's the paleo life going?

### ISSUE THREAD

**Issue by spences10** [wesbos/ama#188]
Hey @wesbos 👋 

You mentioned on the syntax.fm podcast you were going paleo, I wanted to ask how you are finding it so far and also I was slightly concerned as to what may happen to all your craft beer.

Actually it's just about the beer 🍺 

What are you going to do about the beer @wesbos you can send it to me if you like ❤️

**Comment by wesbos** [comment]
Haha good question - I've been Keto (similar to Paleo) for about 3 weeks now and it's going great. I've lost about 9 pounds so far.

I'm trying to limit myself to around 20-30 carbs/day which keeps you in nutritional ketosis.

What I've been doing is having a _really nice_ beer when I'm on a date with my wife and making it totally worth it. I can usually stay within the 20-30 carbs with this.

There are also some beers like michelob ultra which have 2-3 carbs per beer, so I can have those too. 

The funny thing is that this keto thing has made me even more of a lightweight, so 2 beers in and I'm ready for bed!

**Comment by spences10** [comment]
Good work 👍 

And I'm glad you're not following it to the letter, i.e. no beer around in paleo times

It's basically carbs, they be the devil! 👿 

Good luck with the new regime and the gains that come with it 💪 

Are you on a schedule for the gym now as well @wesbos ??

Do you schedule your meals around workout times at all?

**Comment by wesbos** [comment]
Yep - I workout 4x a week right now - just lifting heavy things for now. 

No scheduling of meals - that is too hard with a family :)

**Comment by spences10** [comment]
@wesbos what I should have asked (what I meant actually) was "do you have a set schedule for going gym?"

I'm guessing from your reply you possibly go Mon, Tue, Thu, Fri?

How do you work that into your day? Do you go first thing in the morning for lunch or in the evening?

That has always been one thing I have struggled with I could never really get to a gym early enough so I was always left with lunch or after work

I always found if I trained after work, not only did I not see my family but I was usually up all night after training because my adrenals we always fired up

**Comment by wesbos** [comment]
I train M,T,W,T usually. 

I hate missing work, but in order to make it work I need to go twice a week during the day, and twice a week at night.  I'm slowly realizing that being in good shape will help my work. So I lose an hour twice a week but I think I gain that back from greater focus the rest of the week. 

Sleeping is usually not a problem for me, though I do like taking a pre-workout every now and then and getting some serious pump, and that doesn't fly during evening workouts.

**Comment by spences10** [comment]
>I'm slowly realizing that being in good shape will help my work. 
👌 

Wow! You know what, I think you have just helped me understand why I have been in such a slump for the last few months now!!

I don't know what it was that motivated me before but since I have started dedicating all my spare time to learning to code my diet has taken a real turn for the worse 🙃 

I train three times M,W,F but I have been on autopilot for ages going through the motions, I spent a good four years training religiously and have undone all that good work with 9 months or so of bad nutrition (I was pretty ill at the beginning of the year) 

This needs to change! 

Wow, @wesbos the agony aunt!!

Thanks man 👍
