### ISSUE TITLE
What do you smoke that you need a thermometer for?

### ISSUE THREAD

**Issue by filipekiss** [wesbos/ama#189]
Hey, Wes!

I was reading some [Great Qs][great-q] and came across #156, where you mention a thermometer for smoking. What do you smoke that requires such precision? I'm a smoke-fan myself (Cigarettes, Hookah, Vape) and I'd love to know more about this hobby of yours :)

[great-q]:https://github.com/wesbos/ama/labels/Great%20Q%21

**Comment by tdmalone** [comment]
He might’ve meant smoking meat, as opposed to grilling it ;)

**Comment by filipekiss** [comment]
@tdmalone Oh! I've never heard of smoking meat (maybe because I'm not a native english speaker) but that makes so much sense! Thank you hahaha.

**Comment by wesbos** [comment]
Haha yep! Not smoking any sort of drugs or anything :) Just Meat!
