### ISSUE TITLE
What percentage of your day do you spend solely learning?

### ISSUE THREAD

**Issue by vazquez** [wesbos/ama#19]
vs. creating, teaching, writing, etc.

**Comment by wesbos** [comment]
Good question - it really depends on what I'm doing that day. Some days are entirely just for exploring, and others are entirely coding. The amount of time where I sit down and "learn" something probably isn't as frequent as you might think, it's more learn-as-you-go where I need to know some tech for a client project, so I may spend a few hours before doing tutorials, but most of the learning comes from actually building the thing that I need.
