### ISSUE TITLE
Do you plan to launch another course like your Javascript30?

### ISSUE THREAD

**Issue by raynesio** [wesbos/ama#190]

**Comment by wesbos** [comment]
Yeah! The format has had a huge amount of positive feedback so I'm definitely going to so something like it again.

Anything specific you were looking for?

**Comment by tylerbhughes** [comment]
I’d love to see a React30.

**Comment by raynesio** [comment]
React would be awesome definitely :) @wesbos @tylerbhughes

**Comment by mt-webdev** [comment]
Even though i am more the angular guy, I would love a React30 ;)

**Comment by nozzlegear** [comment]
Put me down for a React*Native*30 🤷‍♀️

**Comment by JosNun** [comment]
Testing30 is something I could get behind.
