### ISSUE TITLE
You're now using VS Code?? What prompted you to make the switch from Sublime Text?

### ISSUE THREAD

**Issue by jdlawrence** [wesbos/ama#193]

**Comment by wesbos** [comment]
Yes! I recorded a whole podcast on this topic - check it out! 

https://syntax.fm/show/012/why-is-everyone-switching-to-vs-code

**Comment by mohitsinghs** [comment]
Last time, I was convinced to switch but then intellisense worked when I tweaked Typescript plugin of Microsoft. I installed node.js and few other typings and now I have exactly same intellisense as VCode.
So, Maybe sometime in future I will join VSCode club too.
