### ISSUE TITLE
React Unit testing

### ISSUE THREAD

**Issue by KelpDuNord** [wesbos/ama#195]
Wes,
Your react for beginners course is amazing! I would have paid twice the price and I recommend it to anyone I come across who wants to learn.

The material out there for testing is as terrible as the stuff "competing" with your react course.

Any chance you could enlighten us?

Thanks,
You da bes, wes

**Comment by wesbos** [comment]
Thanks a ton! I'm working on some stuff around this right now - stay tuned :)

**Comment by wesbos** [comment]
(TLDR I'm using Jest to unit test and snapshot test )
