### ISSUE TITLE
Are you still using iterm 2 as your terminal ?

### ISSUE THREAD

**Issue by asotog** [wesbos/ama#196]
Hi Bos qq, 

i have been trying https://hyper.is/ for a while this year, it's really cool, but it hangs sometimes, i usually have 1 tab running a tomcat server, another with mongo and my webpack env in another,

I'm thinking to get back to standard OSX terminal app

Thanks,

**Comment by wesbos** [comment]
Hey! 

I've been on Hyper for maybe 8 months now. It's not perfect, but I've been enjoying it! Most of the perf issues I've had have been resolved, but I still hear about others having them - like yourself :)

**Comment by JosNun** [comment]
Would you mind sharing your config file for Hyper? I've tried it a couple of times, but never really got it configured enough to replace iTerm2.
