### ISSUE TITLE
--save-exact for npm dependencies or version up ^ ?

### ISSUE THREAD

**Issue by growdigital** [wesbos/ama#197]
I notice you have a mixture in  your repos and I really don't know which way to go! Some people talking about packages getting a bit mossy, other people saying you'll break stuff it you're not careful… help!

**Comment by wesbos** [comment]
I usually use ^ in my own projects but use exact versions in my tutorials just to make sure that everyone doing the tutorial is on the same version I'm on. 

hope that makes sense :)
