### ISSUE TITLE
How did you prefer Visual Studio Code over Atom?

### ISSUE THREAD

**Issue by Falgun-Meshram** [wesbos/ama#205]
What I want to understand is how as of December 2017 Atom is not ( in your opinion ) not better than Sublime or Visual Studio Code ?
Or is it your personal choice to select Visual Studio Code over Atom?

**Comment by wesbos** [comment]
Atom never had any killer features that drew me to it, but VS Code had so many. We talk about what those features are over here >> https://syntax.fm/show/012/why-is-everyone-switching-to-vs-code

Thanks for the question!
