### ISSUE TITLE
Your bos.af sticker packs

### ISSUE THREAD

**Issue by mii9000** [wesbos/ama#210]
Hi @wesbos,

I was wondering when will you release your next batch of stickers and if its possible to buy your previous designs as well or not?

**Comment by wesbos** [comment]
I will have them again in a month or two. I will likely repeat a few of the older designs and put a few new ones in. Any requests?

**Comment by mii9000** [comment]
I like all your designs so far. 
Will buy all of them if you repeat all of them and TypeScript if possible 😄 
Also it would be nice if you had an email input at bos.af so that interested buyers can be notified as soon as you release a batch.

**Comment by konekoya** [comment]
@Ibrahim-Islam I think you can follow @wesbos on Twitter https://twitter.com/wesbos. He tweets about selling stickers when they're available.
