### ISSUE TITLE
About your car

### ISSUE THREAD

**Issue by gstvomacedo** [wesbos/ama#222]
Hi Wes!! Im glad to see that you answer a lot of questions here, so as a coder and bmw fan:

I saw on your IG that you had buy a BMW X5, this is a such expensive car... Currently, only a little number of developers working full-time to a company has budget to buy one car like this one (facebook, google and other big companies employees for example), you believe that developers salaries will increase in the next years? Or it will decrease because of the new employees that market is getting?

Thank you!

**Comment by wesbos** [comment]
Hey :) Between us having only one car and not spending money on gas to commute, it really wasn't that much more expensive than most other SUVs. We bought it used so it was significantly cheaper a new one. 

I have no idea about salaries increasing or not but if you really want a nice car, don't be motivated by industry averages, work hard, move fast and earn it :)
