### ISSUE TITLE
emmet and prettier

### ISSUE THREAD

**Issue by miklax** [wesbos/ama#223]
Hi, couldn't find the answer in previous posts.
1. what is exactly the name of the plugin that you are using in vscode that do work like a emmet (maybe it is a variation of emmet). I saw that it is working when you are writing JSX and it looks pretty handy. 
2. I'm using Airbnb eslint config. Do you know maybe if Prettier could follow eslint rules? 

Thanks.

**Comment by wesbos** [comment]
Hey! 

1. 

It's just Emmet. use this to turn it on in JSX:

```
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
```

2. I use Prettier via eslint - here are my settings:

https://github.com/wesbos/dotfiles/blob/master/.eslintrc
