### ISSUE TITLE
How do I join your slack? (#Javascript30).

### ISSUE THREAD

**Issue by jyoungcode** [wesbos/ama#225]
Hello, Excuse me. I have a question. How do I join your slack? (#Javascript30) Is this private course? I want to join this channel..

**Comment by wesbos** [comment]
The slack is only open to those who have bought a paid course of mine - so you get access once you buy a course. I hope that helps!

**Comment by jyoungcode** [comment]
excuse me, 
I can't find that paid course of yours in wesbos.com 
I want to buy the paid course.

**Comment by wesbos** [comment]
(I see you deleted your reply, but all my courses are over at wesbos.com/courses) :)
