### ISSUE TITLE
Excuse me, How do I find the the paid course 

### ISSUE THREAD

**Issue by jyoungcode** [wesbos/ama#226]
excuse me,
I can't find that paid course of yours in wesbos.com
I want to buy the paid course.

thank you for reading this comment

**Comment by wesbos** [comment]
wesbos.com/courses :)

**Comment by jyoungcode** [comment]
uh oh.. I found it! ( I don't click to paid course. )

Thank you so much, sir wesbos :) 
Have a nice day :)
