### ISSUE TITLE
Why don't you promote an email list any more?

### ISSUE THREAD

**Issue by mcintyre94** [wesbos/ama#228]
I listened to your Indiehackers interview (after you plugged that podcast on Syntax!) and you mentioned at that time you already had a giant email list. I'm on that list through your courses, but I noticed you don't offer a way to sign up for the list on your blogs - which I think you mentioned in the interview that you did at that time. Out of interest, how come you don't try to sign up blog readers any more, and has that change had the kind of effect you expected?

**Comment by wesbos** [comment]
I turned those off once i launched the book - now with my free courses I use that as my primary way to get people on my list :)
