### ISSUE TITLE
about Getting Things Done - can you give some tips/advice?

### ISSUE THREAD

**Issue by McVenco** [wesbos/ama#236]
I've seen/read you praising GTD in multiple places (your recent list of books on Instagram, Hashnode AMA), and I'm interested in diving into it myself. How did you get into it yourself, and do you have any recommendations or resources (other than reading David Allen's book of course) how to get the best out of the GTD methodology?

**Comment by vjs3** [comment]
I am not sure how much it will be helpful but @wesbos has talked about indirectly in one of the episodes of Syntax (his podcast): https://syntax.fm/show/067/hasty-treat-goal-setting. Not sure if its all part of GTD but IMHO setting goals properly really helps in GTD more efficiently.

**Comment by wesbos** [comment]
GTD is pretty simple - so if you read David's book, you should be able to get 100% of it.  He invented it after all :) 

There isn't much past that - just start creating tasks and doing them. It's easy to get caught up in learning techniques but I find it's often a distraction for actually doing the work.
