### ISSUE TITLE
Recruiters

### ISSUE THREAD

**Issue by mconnor** [wesbos/ama#240]
I have yet to meet a recruiter who knows there is a difference between javascript and java? How can this be?  Do they exist?

**Comment by wesbos** [comment]
I think recruiters are like real estate agents - the bar to entry is extremely low and the possible payouts are extremely high. They are many good ones, but way more that are just stabbing in the dark hoping to make a $20k payout. 

Where to find them? I'm not sure - I don't deal with recruiters at all :)
