### ISSUE TITLE
How to learn to make a site like twitter?

### ISSUE THREAD

**Issue by chris567** [wesbos/ama#249]
What languages would I need to learn / in what order etc.?

**Comment by wesbos** [comment]
Hey - you'll need to learn a whole bunch of stuff. I got your email and I don't want to discourage you, but the skillset needed for this takes years to develop. Basically  you'll need everything.

If I were doing it:

Backend - Node.js express
Data - GraphQL
Frontend- react.js
Database - mysql or postgres

Each of these things youll go down a rabbit hole of best practices and tools for each one. 

So - I can't really answer this other than saying "everything :)"

**Comment by chris567** [comment]
Thanks so much for responding! Really appreciate your input. Agree on
Node.js and Express.  Not sure why I would need GraphQL.  Would it be
easier if I used EJS instead of React, and socket.io instead of ajax (once
login credentials are verified)?  How about sqlite instead of Postgres?
