### ISSUE TITLE
What are your TweetDeck filters?

### ISSUE THREAD

**Issue by deadcoder0904** [wesbos/ama#256]
You said https://github.com/wesbos/ama/issues/128#issuecomment-272192369 that you use lots of TweetDeck filters & are a power user of it.

I'd love to know what those filters are?

I don't have a lot of followers but filters in the topic I'm interested in would be a better way to use Twitter.

**Comment by wesbos** [comment]
It's all personal preference - things I either don't care about or don't care to see people argue about on twitter. I also liberally mute or block people who are jerks - no time for that! 

I'd share a list, but I don't care to get into it with people :) 

It breaks down into a few categories:

1. All Airline handles. People love to complain about a delayed flight on twitter. That really sucks, but I don't care that much :) 
1. politics - anything surrounding Canadian or American politics. I care about this stuff, but twitter isn't the place where I want to listen to people bicker. I have other news outlets for when I need to stay informed about this stuff.
1. Movies and video games - I care zero about these things
1. Sports - NBA, NHL, raptors, leafs, drake, etc.. Don't care again.
