### ISSUE TITLE
Re-record of Advanced React

### ISSUE THREAD

**Issue by chopfitzroy** [wesbos/ama#271]
Hey Wes,

I wondered if there was an ETA on the re-record for your advanced React course with GraphQL?

Additionally I was wondering have you stuck with Yoga + Prisma, or are you now using Apollo Server 2 + Prisma (or another ORM)?

Also will the re-record be taking advantage of React hooks, especially in regards to React Apollo Client?

Cheers!

**Comment by wesbos** [comment]
Not yet - still working through it and there are lots of moving parts - new Next.js coming out, new Apollo Client... 

It will likely be Keystone.js instead of Prisma. Prisma is great but prisma 2 isn't out yet and there is no sense in doing it in prisma 1

And yah - 100% hooks :)
