### ISSUE TITLE
What's your keyboard shortcut set up?

### ISSUE THREAD

**Issue by devjusty** [wesbos/ama#279]
Howdy Wes, 

I've heard you mention your keyboard replacement shortcut set up in multiple eps of the pod, but didn't see it in any show notes or answered here. Do you have any particular short cut customizations that you'd recommend?

**Comment by wesbos** [comment]
Great Question! I use Karabiner Elements to Map Caps lock to ⌘ + Ctrl + Option + Shift.  This is known a "Hyper" key

Then in various projects I use Hyper + Whatever to make commands. 

Like in VS code Ill set Hyper + H to hints

I also use Better Touch tool to setup a few window reorg shortcuts and launch apps. Most of these are Hyper + some key.
