### ISSUE TITLE
How do you manage your bookmarks? 

### ISSUE THREAD

**Issue by devjusty** [wesbos/ama#280]
Hi Wes, back with another Q. How do you manage your bookmarks? Any tips for organizing resources for assets, documentation, and all of the the other fun stuff you visit regular or want to come back to?

**Comment by wesbos** [comment]
I don't really. Sometimes I put links to stuff in markdown docs when im doing research on a topic. Other than that I use the browser bookmarks and every now and then I just nuke them and start again. It becomes a mess otherwise :)
