### ISSUE TITLE
what programming language would you suggest?

### ISSUE THREAD

**Issue by robbbz** [wesbos/ama#29]
I am a javascript developer programming node and browser-side. Except PHP I don't know any other back-end languages. I want to learn something that I can use for web applications, but also just for other kind of programming. What language would you suggest me to use?

**Comment by wesbos** [comment]
I'm in the same boat as you - I grew up on PHP and I switched to Node about 4 years ago. 

I'd say stick with 100% JavaScript. I'm a big fan!
