### ISSUE TITLE
What's the best programming related book you've read and why?

### ISSUE THREAD

**Issue by sindresorhus** [wesbos/ama#3]

**Comment by wesbos** [comment]
I don't really read programming books - but one book that gave me amazing clarity was JavaScript Patterns → <http://shop.oreilly.com/product/9780596806767.do>

I watch tons of videos, and I back in the day the Backbone.js and the Node.js ones from Peepcode were amazing. Today I'm a big fan of EggHead.io's videos.

**Comment by macshaggy** [comment]
What would be a great JavaScript book for someone who has programmed in C, C++, Java?

**Comment by zohaibr** [comment]
@macshaggy I would say a combination of http://eloquentjavascript.net/ and https://github.com/getify/You-Dont-Know-JS/.
