### ISSUE TITLE
Favorite shortcut on your laptop?

### ISSUE THREAD

**Issue by robbbz** [wesbos/ama#30]

**Comment by wesbos** [comment]
I'd say there are a few simple ones

`⌘` + `TAB` to switch apps
`⌘` + ``` ` ``` for switching between multiple app windows

and I've remapped my Caps Lock key to Divvy. I wrote a post on it here → http://wesbos.com/remap-capslock-osx/

**Comment by drewrawitz** [comment]
@wesbos Have you ever heard of [Phoenix](https://github.com/kasper/phoenix)? I used to use Divvy until I found Phoenix, which is a lightweight OSX Window manager scripted in Javascript.  So you can have your phoenix.js file as part of your personal dotfiles, so wherever you go you'll have your keybindings and shortcuts with you.

**Comment by wesbos** [comment]
@drewrawitz I haven't! I used Slate for the longest time and wrote my own key bindings with JS, but the project died. 

I really like the simplicity of Divvy, but I'll take a look at this one. Thanks!
