### ISSUE TITLE
Why do you suggest oh my zsh?

### ISSUE THREAD

**Issue by robbbz** [wesbos/ama#33]
OMZSH was cool years ago but it's not really a cool kids thing anymore right?

I always thought it was better to use something like https://github.com/sindresorhus/pure and [not](https://twitter.com/sindresorhus/status/614148112458891265) OMZSH.

**Comment by wesbos** [comment]
Cool should never have anything to do with a technology choice. You should pick something that works for you. I'm sure pure is great - I really like oh my zsh and I've never run into any issues with with it!

**Comment by robbbz** [comment]
Do you ever get to work on big repos? It's sooo fat and slow.
