### ISSUE TITLE
px or em based media queries?

### ISSUE THREAD

**Issue by MandyMadeThis** [wesbos/ama#35]
I asked [Drew](https://github.com/drewminns/ama/issues?q=is%3Aissue+is%3Aclosed) this one too, but I'm also curious to know your opinion. I keep flip flopping...

**Comment by wesbos** [comment]
Most of the time I'll use px, but many of my projects use em.

I really couldn't care less what people use. :smile:  They both do the same thing and there is no benefit to using one over the other. 

It used to be only em-based MQ worked with zooming - but that has been fixed. So you either do the em calculation in your head for what px breakpoint you want, or you just use pixels. 

Unless you wanted to magically move every MQ up a few levels by changing the root font size, there isn't any benefit. 

So, use whatever you want! At the end of the day your website is not better from either one. Your client is not selling more widgets, your code is not more maintainable. 

I see these questions / arguments a lot and I really prefer to spend my time on learning other stuff and <http://justbuildwebsites.com/>

**Comment by MandyMadeThis** [comment]
Nice! Thank you! Putting this issue to rest (in my own head). I'm going back to pixels and I not going to worry about it anymore.
