### ISSUE TITLE
What do you think about Sublime Text Build System?

### ISSUE THREAD

**Issue by oscarmcm** [wesbos/ama#39]

**Comment by wesbos** [comment]
I think it's great that we can trigger build systems and pipe the console result back into the editor, but I've always felt they are a bit wonky. 

I much prefer to have a full blown terminal and use something like Gulp or Grunt to  run my build systems. 

If you use Gulp, there is a fantastic Sublime Text plugin that will allow you to run gulp tasks as a build system - pretty handy!

**Comment by oscarmcm** [comment]
Awesome!!! :smiley: thanks :+1:
