### ISSUE TITLE
Favorite front end framework?

### ISSUE THREAD

**Issue by lukebro** [wesbos/ama#41]
Q: **What is your go to / favorite front end Javascript framework?  Angular? Ember?**

Also as a sub-question:
**What is your opinion on [Vue.js](http://vuejs.org)?**

**Comment by wesbos** [comment]
I learned on Backbone, but right now it's Angular and moving toward React, but it really depends on what the client needs. 

I think Angular is super easy to get started with and will work for most use cases - I don't understand all the negativity about it. 

I've never seen Vue.js before - looks like another framework - it's great to see the JS community so bumpin' right now. Some great ideas are rising to the top!
