### ISSUE TITLE
Why do you dislike PHP?

### ISSUE THREAD

**Issue by lukebro** [wesbos/ama#42]
I've seen some tweets or read somewhere that you said you're not a fan of PHP, more specifically that it isn't "cool" and it's "not nice at all".

Just curious where did this opinion come from?  Any bad experiences with PHP?

And since you don't like PHP, **what is your favorite back end language?**

Personally I think PHP is one of the nicer languages that really has come a long way in the last 5 years.  Any interpreted language is cool in my book (Python included).  But to each his own, right? :smile:

**Comment by wesbos** [comment]
While I don't like it - I still use it quite a bit. Me not liking it doesn't mean it's not a powerful language - it can do anything any other language can do! 

So why don't I like it? I'm just in love with the Node.js ecosystem. For me, it's the modules and the ability to get something up and running so quickly. I think it's similar to why rails people love ROR so much. 

That, and the syntax isn't my favourite.

So yeah - maybe I shouldn't have said it's not nice at all, but it's just not my number 1 choice when I go to build something. I do agree PHP has changed quite a bit in the last few years - I'm excited to see where it goes.
