### ISSUE TITLE
What do you use for domain/hosting/blogging providers?

### ISSUE THREAD

**Issue by victormejia** [wesbos/ama#46]

**Comment by wesbos** [comment]
Domains are mostly on either Godaddy or Hover - I've been on Godaddy for domains for about ~12 years  but now I'm moving things over to hover as a renew, but I don't really care too much about where it's registered - doesn't affect my site perf at all. 

For Hosting... 

I run LAMP / WordPress Hosting on Bluehost
I run most of my Node apps on Digital Ocean
I use Mandrill and SES to send emails
I use MongoHub to host my mongodb databases
