### ISSUE TITLE
what's your detailed website development process

### ISSUE THREAD

**Issue by girishpatil** [wesbos/ama#47]
hey I love your talks,post , wtflexbox and you motivate me a lot .. :)
I completed my first website a kind of web app and god knows the troubles I faced. I changed the themes I designed for about 10 times( I kinda feel bored when I keep on looking at those themes again and again) .I would like to know what are your steps in building websites.do you feel bored at the designs you develop or am I the only one. Thank you.

**Comment by wesbos** [comment]
wow I left this one for 364 days! 

This is a bit of a big question so I'm not going to answer it here but I should record something soon!

**Comment by girishpatil** [comment]
waiting for that thank you
