### ISSUE TITLE
What is your opinion of the tech scene in Toronto? Of the city in general?

### ISSUE THREAD

**Issue by RichardLitt** [wesbos/ama#54]

**Comment by wesbos** [comment]
Toronto is amazing. I owe a lot of my first few years to the Toronto tech scene. 

Fantastic meetups, conferences and lots of really good developers always interested in chatting about web development. 

I live in Hamilton now - which is about 45 mins outside of Toronto, but I'd still consider myself a big part of the Toronto tech scene. 

Thanks for the question 👌

**Comment by RichardLitt** [comment]
Thanks for answering!
