### ISSUE TITLE
Have you ever tried Polymer?

### ISSUE THREAD

**Issue by HoBi** [wesbos/ama#58]

**Comment by wesbos** [comment]
I've been following it pretty closely, but I haven't used it in any projects yet. 

The idea of web components just makes a lot of sense to me, and I really enjoy using React components. 

So I'm on board, I just haven't had a project yet. 

I think we're seeing a big uptake in build systems for front end dev right now and that is going to set the stage for everyone using NPM modules for their front end JS and CSS.
