### ISSUE TITLE
In which resolution do you record screencasts?

### ISSUE THREAD

**Issue by martinwolf** [wesbos/ama#59]
Hey Wes,

I'm recording screencasts too and still have trouble finding the right resolution. I have a 27" display and recording in 2560x1440 is not really ideal because everything is really small for people watching it on smaller displays. Do you switch your display to a lower resolution for recording or do you just record a specific area of your screen?

Looking forward to hearing how you do it.

Thanks,
Martin

**Comment by martinwolf** [comment]
Oh, I found the answer in this question/answer:
https://github.com/wesbos/ama/issues/26

Thanks!

**Comment by wesbos** [comment]
Yep - now that I have a hi DPI monitor, the resolution is a little higher, but everything is still scaled for 1080p - I find it to be just enough space for people to watch it and code at the same time.

**Comment by martinwolf** [comment]
Thanks! Tried only recording a portion of the screen today, worked perfectly:
https://www.youtube.com/watch?v=Pw32ATaIiy0
(Warning, it's in german. :D)

Cheers,
Martin
