### ISSUE TITLE
What would you do today if you didn't do programming?

### ISSUE THREAD

**Issue by sindresorhus** [wesbos/ama#6]
Let's say in an alternate universe where you never discover programming.

**Comment by wesbos** [comment]
I think I'd still be running a business, but something that is less glamourous than web development (is it even glamorous?!)  And something where I can still interact with lots of people and share what I know. 

Home Renovator
Table linen rental company
Broom maker
Hammock maker

It's a great question - I often think about what it would be like to build a business in an industry that I know nothing about.
