### ISSUE TITLE
Future plans about making Reract.js videos series ?

### ISSUE THREAD

**Issue by bhaveshgohel** [wesbos/ama#60]
I really loved the style of your teaching, it's always to the point. I have watched Flexbox and Command Line Power User series. 

Do you have any future plans about making Reract.js videos series ?
Thanks. :smiley:

**Comment by wesbos** [comment]
I assume you mean _React.js_, right?

I am creating one and it's almost done. I had a bad cold which stopped me from recording before I went to a conference, so I'm finishing it all up next week and you should see it soon!

**Comment by bhaveshgohel** [comment]
WoW.. Great! Waiting for it... :+1: 

--
Typo Fixed! :smile:
