### ISSUE TITLE
Best books for learning JavaScript

### ISSUE THREAD

**Issue by lalwanivikas** [wesbos/ama#61]
Hello Wes!

Loved your reply [here](https://github.com/wesbos/ama/issues/37) that the best way to learn JS is to make 1000 little things. But I believe sometimes reading good books also helps in getting the fundamentals right. So just wanted to know if there are any great books for learning JavaScript or general front-end dev that you would recommend?

Books advice on any level (beginner/intermediate/advanced) are welcome :) Thanks!

**Comment by wesbos** [comment]
Good question - there are so many good ones out there. I personally find watching video tutorials works better for me. 

As far as books go, when I started I read JavaScript the Good Parts and Stoyan Stefanov's Javascript Patterns - they were both pretty big for me. I've heard from a lot of our students at HackerYou that JavaScript the good parts isn't a great introduction to JS, but better read once you grasp the basics. 

Right now I'm absolutely loving [Exploring ES6](https://leanpub.com/exploring-es6/) by @rauschma  - it's a really indepth look at at the pieces of ES6. 

I've heard lots of people enjoy @getify's YDKJS → https://github.com/getify/You-Dont-Know-JS

Past that I can't really chime in too much about books, so I'm going to open this up to anyone else who has a recommendation. 

Anyone?

**Comment by jdhancock88** [comment]
Javascript and Jquery, by Jon Duckett

http://www.amazon.com/JavaScript-JQuery-Interactive-Front-End-Development/dp/1118531647

**Comment by wesbos** [comment]
Ah yes - lots of my students LOVE that one. It's incredibly well laid out.

**Comment by michaelryancaputo** [comment]
Been enjoying JavaScript with Promises - http://shop.oreilly.com/product/0636920032151.do

**Comment by atuttle** [comment]
JavaScript: The Good Parts was transformative for me. It's small enough that even people that generally don't learn well from books (i.e. me) can get through it without losing motivation/momentum, and it's jam-packed with goodness.

http://amzn.com/B0026OR2ZY

**Comment by davemo** [comment]
This isn't a book but I found most of the knowledge from "JavaScript the Good Parts" was much easier to understand on YUI Theater back in the day. They've since moved all of their videos to YouTube but this playlist titled [Crockford on JavaScript](https://www.youtube.com/watch?v=JxAXlJEmNMg&list=PL7664379246A246CB) is fantastic!

**Comment by theaemarie** [comment]
It may be a little silly, and I'm not a 'kid', but JavaScript for Kids was EXCELLENT. Great introduction to basic concepts that other more advanced books tend to over-explain.

http://www.amazon.com/JavaScript-Kids-Playful-Introduction-Programming/dp/1593274084

**Comment by atom-morgan** [comment]
Two of my favorites: [Single Page Web Applications: JavaScript end-to-end](http://www.amazon.com/Single-Page-Applications-end-end/dp/1617290750) and [The Principles of Object-Oriented JavaScript](http://www.amazon.com/Principles-Object-Oriented-JavaScript-Nicholas-Zakas/dp/1593275404/ref=pd_sim_14_4?ie=UTF8&refRID=15DM85C755QZM2GVC7PN&dpID=51%2BUy4JxjVL&dpSrc=sims&preST=_AC_UL160_SR121%2C160_). I'm still working my way through the [YDKJS](http://www.amazon.com/Kyle-Simpson/e/B006MAHIQ6/ref=sr_ntt_srch_lnk_1?qid=1445523787&sr=1-1) series but that's also looking to be great.

**Comment by mindcrash** [comment]
[Eloquent JavaScript](http://eloquentjavascript.net) by Marijn Haverbeke

**Comment by ArmendGashi** [comment]
My favorites
* [Eloquent JavaScript](http://eloquentjavascript.net) by Marijn Haverbeke 
* [Principles of Object-Oriented Programming in JavaScript](https://leanpub.com/oopinjavascript) By Nicholas C. Zakas
* [JavaScript Patterns](http://shop.oreilly.com/product/9780596806767.do) By Stoyan Stefanov
* [Human Javascript](http://read.humanjavascript.com) By Henrik Joreteg
* [Exploring ES6](https://leanpub.com/exploring-es6/) By Axel Rauschmayer
* [Node in Action](https://www.manning.com/books/node-js-in-action) By Mike Cantelon, Marc Harter, T.J. Holowaychuk, and Nathan Rajlich


DOM
* [DOM Enlightenment](http://domenlightenment.com) By Cody Lindley
* [jQuery in Action, Third Edition](https://www.manning.com/books/jquery-in-action-third-edition) By Bear Bibeault, Yehuda Katz, and Aurelio De Rosa
* [Mastering jQuery](https://shop.smashingmagazine.com/products/mastering-jquery-1) By Smashing Media GmbH

Animation
* [Foundation HTML5 Animation with JavaScript](http://www.apress.com/9781430236658) By Billy Lamberta , Keith Peters
* [JavaScript Creativity](http://www.apress.com/9781430259442) By By Shane Hudson

**Comment by dydx** [comment]
Any love for [Reginald Braithwaite](@raganwald)'s [books](https://leanpub.com/u/raganwald)?

I got a lot of mileage from [Spessore](https://leanpub.com/javascript-spessore) and [Allonge](https://leanpub.com/javascriptallongesix)

**Comment by ldong** [comment]
I definitely recommend all mid-level developers to advance their skills by reading [Pro JavaScript Techniques](http://www.amazon.com/Pro-JavaScript-Techniques-John-Resig/dp/1590597273/ref=asap_bc?ie=UTF8) by @jeresig

**Comment by swennemans** [comment]
Not JS specific but [Exercises for Programmers](https://pragprog.com/book/bhwb/exercises-for-programmers) could be very helpful. For me with just reading books it never clicks. I can have the illusion that I understand it, until I have to apply it in the correct situation. What I need it exercises but I can be an easy trap to solve the same type of problem over and over again (for example UI related stuff). This book offers a diversion in exercises that can be extremely helpful. It makes you reread the chapters of your programming book(s) of choice. 

Plus it has a ton of replay value for every new language you want to learn in the future, or known language you want to improve.

**Comment by wesbos** [comment]
Wow - thanks everyone. Some fantastic suggestions in here - a few I want to now read myself!
