### ISSUE TITLE
what's your favorite/most-effective learning method?

### ISSUE THREAD

**Issue by ahmadnassri** [wesbos/ama#62]

**Comment by wesbos** [comment]
My process is entirely learn by doing - that is why all my training products always build something or are filled with lots of real world examples.

Usually when I tackle something new, I'll spot-read a couple of blog posts and then get into the code as quickly as possible. 

Same goes for my non-technical skills that I'm trying to refine, like cooking. I just watch lots of youtube videos or cooking shows, scan a few recipes, and then try it out myself.  

After you have coded an app in flexbox or cooked a chicken in the oven, you get the hang of it and it becomes the basis for the next thing you want to learn.
