### ISSUE TITLE
What do you use for bug tracking?

### ISSUE THREAD

**Issue by infn8** [wesbos/ama#65]
I've used bugzilla before in a corporate setup.  It's ok
I'm using freshdesk now on a small team.
I've tried osticket

They all WORK but they're all just OK

* Bugzilla
    * UGLY
* Freshdesk
    * Pain in the butt to get multiple people on the same ticket
* OSTicket
    * Tonnes of setup effort

Any others you use or have tried?

**Comment by wesbos** [comment]
Depends on the client really - I've used everything from a Trello board (which I a big fan of) to JIRA. For my personal stuff I use Github issues.
