### ISSUE TITLE
As someone that is looking at getting into screencast, what software would you recommend?

### ISSUE THREAD

**Issue by rclanan** [wesbos/ama#66]

**Comment by wesbos** [comment]
Screenflow is what I use - it's fantastic and well worth the pricetag.

More info here: https://github.com/wesbos/ama/issues/26

**Comment by rclanan** [comment]
Wonderful, thanks for the reply!

**Comment by rclanan** [comment]
Link for others to reference: http://www.telestream.net/screenflow/overview.htm
