### ISSUE TITLE
Your repo "Simple Redux"

### ISSUE THREAD

**Issue by anselmdk** [wesbos/ama#68]
I just bought your "React for Beginners" course and am looking forward to watch the videos.
I'll be working on building an App using React and Redux in the coming months, which is why I bought your course for preparation. Because we'll be using Redux, I'm interested in what's up with https://github.com/wesbos/Simple-Redux - any hints? :)

**Comment by wesbos** [comment]
You are soo sneaky! I'm working on a free followup series for people to build a redux app. That is just my progress on trying to build something that is simple and understandable.

**Comment by anselmdk** [comment]
Sounds great - looking forward!

**Comment by martinvd** [comment]
:+1:
