### ISSUE TITLE
HTML5,CSS3,JavaScript

### ISSUE THREAD

**Issue by nedcode** [wesbos/ama#69]
Hello I have one very important question to ask for my job future.I have started learning HTML5,CSS3,Javascript.It is going all well up till now.I am two months in it.I want to work as a front-end developer.But there are more and more texts of the possibilities that these technologies are replecable and soon to be dead and not in use.

My question is - is it worth it learning all of this and creating websites when there are things like that GRID automation software system soon to override the market?

**Comment by wesbos** [comment]
This question gets asked a ton in our space - companies like SquareSpace and the grid will probably replace the need for simple brochure websites, but if you have skills in HTML CSS and JS, your won't be jobless tomorrow. 

Just like any industry, if you keep up with the current trends you will be totally fine. It's only when you stagnate in your learning where you will get in trouble. 

Sounds like you really like this stuff, so keep doing it and things will work out!
