### ISSUE TITLE
What would recommend to someone starting teaching online?

### ISSUE THREAD

**Issue by amejiarosario** [wesbos/ama#73]
Hey Wes,

I first came to know about your work through [What the Flexbox!?](http://flexbox.io/). Watched every single one of them. Thanks for putting that together!
I also noticed that you have some other ones: [Command line power user](http://commandlinepoweruser.com/)... They are great and also free. How do you make revenue out of them? 
And also, I saw the sublime text books/videos, my second question is, how do you make your own books and what software/hardware do you use for producing the videos?

**Comment by wesbos** [comment]
Good question! 

The free ones are used to establish an audience, rapore with people like yourself, and introduce my teaching style to people who may be interested in more, but need to know that we click first. 

They don't make money directly, but many people who enjoy the free ones go on to purchase one of my paid ones. I've got a list of [all my courses here](http://wesbos.com/courses/).

The book is written in markdown and converted to HTML and then to a PDF with Prince CSS. 

I wrote a bit about my hardware setup here → http://wesbos.com/uses

Hope that helps!
