### ISSUE TITLE
What surprising things did you learn about Redux while making your tutorial series?

### ISSUE THREAD

**Issue by radiovisual** [wesbos/ama#75]
Everyone learns something new when they set out to teach a subject. So what were some of the cool things you discovered about Redux while making your new ["Learn Redux"](https://learnredux.com/) video series?

**Comment by wesbos** [comment]
great question - thanks for asking it! 

One thing I confirmed is that it's often worth the extra work upfront to make things easier. Redux is tough to get started with, and it's a lot of work to get setup. Once you have it setup, things get really easy for you as the app developer. 

I also learned or solidified a bunch of things about functional programming that were a bit hazy before — pure functions, state mutation, immutability etc..

**Comment by ryandury** [comment]
It's amazing how difficult it seems at first.. Now in practice it's hard to look back and understand why, because it's fairly straightforward.  I wish I discovered and learnt it sooner :)
