### ISSUE TITLE
GitHub AMA reader feedback?

### ISSUE THREAD

**Issue by akashnimare** [wesbos/ama#76]
I love reading AMAs. It's kind of annoying when I have to open each issue in a new tab. So I have made a little app [here](http://akashnimare.in/ReadAMA/). Any suggestions to improve this?
https://github.com/akashnimare/ReadAMA

**Comment by gethinoakes** [comment]
That's awesome!

**Comment by wesbos** [comment]
p cool! I added an issue on your repo with some feedback :)

**Comment by akashnimare** [comment]
Yes. Thanks :)
