### ISSUE TITLE
How did you get started working for yourself?

### ISSUE THREAD

**Issue by jonathanpike** [wesbos/ama#77]
Hi Wes, 

I was just wondering how you got started working for yourself after you graduated from Ryerson.  How did you go about getting your first client?  Did you already have a portfolio of work done at that point, or where you starting from scratch?  

Thanks a lot for your AMA!

**Comment by wesbos** [comment]
Thanks for the question! 

I got my first crop of real clients (outside friends and family) through twitter while I was in my 2nd and 3rd year of University. Back in the day (~ 7 years ago) the Toronto twitter scene was very small and I was very involved. I met Satish and Verne from Jet Cooper (which got bought and turned into Shopify Toronto a few years back) and they started to funnel me WordPress work as well as just refer some of the smaller fish my way. 

That turned into meeting dozens more people and it's history. If you can meet enough people and let them know what you do, you'll get plenty of work.

One important point here is that it's not about your portfolio - it's all about how people perceive you. If you tell people you are good, if you come off as a reputable and genuine person, clients will hire you. It's all about making people feel like you will slam dunk the job and help their business grow.

**Comment by raaasin** [comment]
Great Advice Wes!
