### ISSUE TITLE
Your real name

### ISSUE THREAD

**Issue by klikstermkd** [wesbos/ama#79]
Hey!

Maybe this is a silly question, but is Wes Bos your real name? :-D 

I'm asking this because I have never heard of a name like yours before.

**Comment by wesbos** [comment]
Ahahaha. It's Wesley Bos, but I've gone by Wes forever unless my mom is super pissed at me. 

I love that its so short and memorable. We named our daughter Lux (Latin for Light) so she can have a cool short name too. And yes we bought LuxBox.com before se was born :)

**Comment by wesbos** [comment]
Oh and it's pronounced "Boss", not "Bose"

Like a Bos, not like speakers.

**Comment by kitze** [comment]
Just add one more S at the end so it's complete.

**Comment by carlolaitano** [comment]
Dude.. you have a rockstar name.
