### ISSUE TITLE
What thing you made are you most proud of?

### ISSUE THREAD

**Issue by sindresorhus** [wesbos/ama#8]

**Comment by wesbos** [comment]
I think it's been my book → <SublimeTextBook.com>

It's been out less than a year but it's totally changed my career.

The money from the sales has let me focus on creating more awesome tutorials, training, talks and books, which is fantastic. 

The confidence it's given me is unreal. I'm really trying to make this whole teaching-the-web thing my entire business, and it's shown me that it's totally possible by just mixing hard work and helping people!

**Comment by artemist** [comment]
:+1:

**Comment by sindresorhus** [comment]
:+1:

**Comment by EddyVinck** [comment]
Is your book still the thing you are most proud of?

**Comment by wesbos** [comment]
JavaScript30.com is def the thing I'm most proud of - just from the amount of feedback I've received it's nuts - new jobs, salary increases and overall better understanding of JS

**Comment by codercatdev** [comment]
I have been writing JS for years, and yet am learning so much from JavaScript30.com...it is kinda nuts!
