### ISSUE TITLE
Balancing side projects and client projects

### ISSUE THREAD

**Issue by andela-smartins** [wesbos/ama#80]
Hi Wes,

How do you balance doing side projects (including contributing to open source, learning new frameworks, writing books, creating videos) with actual client projects without over-working yourself.

**Comment by nicekiwi** [comment]
+1

**Comment by wesbos** [comment]
Good question - I think it can be summed up in three things

1. **Finish things you start** - I've always admired people like @addyosmani who seem to put out an incredible amount of high quality work. Slowly I've realized that people like this are just good finishers - they see a project through to the end and push past that last 10% when it seems to not be so much fun anymore. 

2. **If it's not a hell yes, it's a no** - this is a quote from [Derek Sivers](https://sivers.org/hellyeah). Only do things that you are 100% stoked about. I'd add that you should also take on things that make your stomach tie in knots - that means you are pushing yourself. Take on things that are exciting and a little outside your realm. 

3. **Make time to do it** — Everyone is busy and no one has enough time. If you really think these things are important for your career, then do them. If you leave them to "If I have time" it's not a priority. When I did client work, I would block off a few days a week/month to devote to learning/making/writing. It cost me lots of $$ in client billing, but was well worth it! 

👊👊👊
