### ISSUE TITLE
request for Sketch course

### ISSUE THREAD

**Issue by BilalBudhani** [wesbos/ama#81]
Hi Wes, 

I really like the way you teach in your courses. I'd really like to learn Sketch till the point, where I can do mockup designs and translate my thoughts into a visual design. It would be great if you can do a course on Sketch. 

Thanks,

**Comment by wesbos** [comment]
Great suggestion  - I've been mulling it around :)

**Comment by BilalBudhani** [comment]
Sounds great @wesbos. I'm looking forward to it. 💥

**Comment by jwalton512** [comment]
Wow, I literally just bothered you on twitter about Sketch.   +1 !

**Comment by wesbos** [comment]
:) It's on my list fellas!
