### ISSUE TITLE
What paid software do you use?

### ISSUE THREAD

**Issue by jkup** [wesbos/ama#83]
I'm curious, with all the great free software out there, what premium applications have made it on to your computer?

**Comment by wesbos** [comment]
Great question! I think these are the main paid ones I use day-to-day

* Marked
* Cloudapp
* Better Touch Tool (for custom capslock shortcuts + window snapping)
* Alfred
* Sublime Text
* Screenflow (screen recording)
* Things (GTD todo app)
* UberLayer - to overlay a 1920x1080 box with common width notches for recording
* Sketch
