### ISSUE TITLE
Why don't you drop text expander ?

### ISSUE THREAD

**Issue by digitalbase** [wesbos/ama#84]
Noticed on http://wesbos.com/uses that you use alfred + textexpander.

Alfred 3 has snippets expansion (https://www.alfredapp.com/help/features/snippets/). 

Any reason why you haven't thrown out textexpander just yet (one less tool) or just haven't gotten to it yet ?

**Comment by jwalton512** [comment]
@digitalbase have had alfred3 for a while and didn't notice this.  going to try it out vs textexpander.  thanks!

**Comment by wesbos** [comment]
The snippet expansion is great, but OSX also has that built into. Text expander has tons more features:

* Auto capitalization.  `:kit` → `keep in touch` while `:Kit` is `Keep in touch`.
* Random Snippets. I have a list of about 40 snippets that when I type something I want to grab one of those 40. 
* Syncing - I need them on my phone too. (although the iPhone text expander keyboard is garbage) 
* Drop downs + fill ins. When I type a snippet, I sometimes need a box to pop up where I can select one of X things from a dropdown
* Clipboard. If I copy your name and then reply to an email, my snippet will have `Hey %clipboard% - thanks for the email!`. 
* Snippet management - I have close to 100 snippets and I need a good tool to manage them

So yeah. I love alfred, but they aren't quite there with snippets yet.

**Comment by Remchi** [comment]
@wesbos that actually changed my mind. I dropped TE about a year ago, now reinstalling it and giving it another chance. Thanks!

**Comment by darrylyoung** [comment]
Also, Alfred doesn't (yet) have the ability to place the cursor in a custom position of a snippet. This, at least for me, is a killer feature.

**Comment by andylima** [comment]
**Auto capitalization** is a must for me as well. The feature I'm missing the most in Alfred! 👍

**Comment by Youmoo** [comment]
@wesbos  

 [Alfred 3 also has clipboard snippets](https://www.alfredapp.com/help/features/clipboard/dynamic-placeholders/) and you can set up a hot key for searching snippets.

**Comment by wesbos** [comment]
In use a Text Expander workflow in Alfred to do something similar - very handy!

**Comment by knilob** [comment]
Following up on this, do you use Text Expander 5 or 6?

**Comment by johnchristopherjones** [comment]
Ever looked at Keyboard Maestro?  It'll let you use JavaScript for Automation in macros and chain them together, pull things in from clipboard, etc. Doesn't have drop downs but it does have palettes.

**Comment by wesbos** [comment]
I'm on Text Expander 5 and will be until they announce new features. Text Expander 6 seems like a bit of a bad deal with the monthly payment. 

I've never used Keyboard Maestro, but I've heard it's amazing for automation.

**Comment by andylima** [comment]
Another **Keyboard Maestro** user and big fan here. I've been using it for many years now... — To me, it is the king of Mac automation. I have many, many small programs / macros created with it that help me on a daily basis.  👍

So I've also started to use Keyboard Maestro for my text expansion needs a few days ago (having dropped TextExpander)...

Still, I feel there's room for a simple and flexible text expansion app in the Mac ecosystem.  There was aText, but it hasn't been updated for one year...

**Comment by ahmadawais** [comment]
@wesbos Where can I find the dump of your TextExpander snippets :P We can barter 📦

**Comment by wesbos** [comment]
They are all very personal so I don't have them public - wouldn't be of use to you. I you type something more than 5 times, or something takes you more than a minute to lookup, make it a snippet!

**Comment by ahmadawais** [comment]
@wesbos I was only joking there 👍 I'm terrible at that!
