### ISSUE TITLE
Do you ever feel tired?

### ISSUE THREAD

**Issue by eddie** [wesbos/ama#85]
It's no secret from following you on twitter that you are super productive..  So..

- Do you ever feel tired? 
- Do you ever work outside of 'office' hours, curious how you fit so much in to your day with having a child etc

Thanks!

**Comment by wesbos** [comment]
hey Eddie - thanks for the question :) 

Do I ever feel tired? Ohh yes. But that is mostly from having a baby who sleeps weird hours sometimes. 

I think the illusion of my productivity has to do with the fact that much of the stuff I do is public. I try and share whatever it is I'm working on at the moment so I've always got something to day.  I also have become really good at deciding what I will take on and finish.

I work from home and I find when I need to commute somewhere, i'm drained. Commuting just kills my energy so I try not to do it. 

I rarely work outside office hours. It's usually about 8:45 → 5pm each day for me except when I teach twice a week @hackeryou - then I also do 6:30-9:30

With a family I almost never work in the evenings and if I do, it's just to rattle off a few emails. I never do work on weekends. I used to do it when I was younger, but I felt I was getting burnt out by the time monday rolls around. Usually I won't touch my laptop all weekend and then by the time monday rolls around I'm feeling good and ready to go for another week.

**Comment by eddie** [comment]
Thanks for answering/sharing @wesbos :)

> With a family I almost never work in the evenings and if I do, it's just to rattle off a few emails. I never do work on weekends. I used to do it when I was younger, but I felt I was getting burnt out by the time monday rolls around. Usually I won't touch my laptop all weekend and then by the time monday rolls around I'm feeling good and ready to go for another week.

This surprises me, but I couldn't agree more-- I don't always listen to myself with this-- but it is a quick way to burn
