### ISSUE TITLE
I have to ask... React or Angular, and why?

### ISSUE THREAD

**Issue by joelseq** [wesbos/ama#86]
I have read a lot of articles that have compared the two and even though most of them state that in the end it's like comparing apples and oranges, I still want to know... which is the superior fruit? :p

**Comment by wesbos** [comment]
Neither! I really dislike when people pick sides and tout one as the best and only option. It really is apples and oranges, and I think it comes down to how you and your team enjoy a framework. 

So - you should try them out and see what fits best for you and your team. I still really like Angular and Angular 2 is looking really great :)
