### ISSUE TITLE
How do you store and organize your notes ?

### ISSUE THREAD

**Issue by sceccaldi** [wesbos/ama#87]
When you see, sketch or think about something interesting, how do you save and organize it ? Gathering ideas and creating the content of your courses require some kind of workflow I suppose ! Could you share how you prepare such content and the tool you use ?

**Comment by wesbos** [comment]
Great question! I use a markdown file and just dump my thoughts into that. As I refine the ideas I break it into sections and add notes for each part. 

It's not much of a workflow and it's not a fancy app, but I like how I can dump everything into a list and then find a spot for it. Specifically when I am ready to record a video series that initial mess of ideas has been refined into a pretty tidy list of videos, each with their own notes.
