### ISSUE TITLE
How would you qualify your server administration skills ?

### ISSUE THREAD

**Issue by sceccaldi** [wesbos/ama#88]
I read you're running your own system on Digital Ocean. Do you feel confortable with administrating your own server ?

I followed several courses on the subject but I'm a little paranoid about security. I always feel that running software on a VPS requires some really advanced server administration skills to do it properly. I use Digital Ocean to run code on my own but never used VPS for production because of this fear.

**Comment by wesbos** [comment]
Digital Ocean images make it pretty simple to get a pre-built box with all the stuff that you need. I know enough to get in there and configure my certs. 

It is a bit of a pain to keep it all up to date, but I'm always interested in learning how these things work!
