### ISSUE TITLE
You have the most succinct and poignant tech tweets! Tell the truth... do you craft and edit them a bunch?

### ISSUE THREAD

**Issue by artemist** [wesbos/ama#9]

**Comment by wesbos** [comment]
Great question! - and yes I do!  I usually craft them in Sublime Text before hand, and take a screenshot that will ensure maximum clicks and retweets.

This question is kind of validating what I'm doing - I hope that people will go back into my past tweets for little nuggets of informations.  For hot tips, I always prepend a 🔥 which helps flag the best things you should check out.

**Comment by artemist** [comment]
I knew it! They're good, man, they're really good. I didn't know that about the fire emoticon, but should have guessed.

**Comment by wesbos** [comment]
:smile: Thanks so much - I'm _really_ glad to hear someone likes them!

**Comment by artemist** [comment]
Oh hells yes, I quote you all the time.
