### ISSUE TITLE
Good at JS dev but terrible at HTML/CSS. Any resources (or care to create them!?)

### ISSUE THREAD

**Issue by bmeneses** [wesbos/ama#91]
Hi Wes - 

I am a pretty experienced JS dev but can't implement a design to save my life. Do you know of any tips/tricks/resources that deal specifically with implementing a full-blown design from either a wireframe or PSD in HTML/CSS, similar to what you'd experience as a front-end dev?

Thanks!

**Comment by wesbos** [comment]
Good question - I don't have any off hand, but I'm sure there are some. 

You can always just go pick up a PSD from ThemeForest and try cut it into HTML/CSS - I mentioned that is how I learned in another AMA. 

Other than that - maybe some people on here can chime in with what they think?
