### ISSUE TITLE
React.createClass vs extends React.Component

### ISSUE THREAD

**Issue by pawelgrzybek** [wesbos/ama#92]
Hi Wes.

I love your new series about ES6 man. Helped me a ton!!!! But thats not my subject today. 

I do a bit of React development. Unfortunately I can't do it at work because I my team is, lets call it "more angular friendly". I don't mind angular but `ng` is an initials of my ex girlfriend so I chose React :)  I build some small bit mainly for myself. I'm wondering about your thoughts about React.createClass vs extends React.Component. Which one do you use in your projects? I know that the `createClass` method is going to be depreciated at some point. From the flip side I don't really feel the concept of Classes in js. It feels for me like a syntax that looks good for dudes that are coming from different languages, but it's not really how js works, yeah? Douglas and Kyle — thanks. Classy way requires more typing as well...

Your thoughts...

**Comment by wesbos** [comment]
I prefer createClass because of the auto binding, but yes it does look like they will deprecate it eventually.  Not a big fan of that, but who knows what will happen!
