### ISSUE TITLE
What do you think about the increasing number of CSS features?

### ISSUE THREAD

**Issue by FezVrasta** [wesbos/ama#93]
Last thing I discovered is the `:matches` pseudo-selector. To me it seems like CSS is growing in a "PHP like" way and I'm scared about the future.

What's your thoughts?

**Comment by wesbos** [comment]
Yeah! CSS is getting hard - the amount we are writing is going up, how we structure it is getting more complex, the features (animation, layouts, special selectors as you have mentioned). 

So what do I think?

1) I think it's just an opportunity for people to specialize in just doing CSS. 
2) you won't need everything all the time - CSS is getting bigger but there are a lot of edge case things that you may not use day-to-day. It's good to know that these things are available, and it's something you can easily reference if you need it.
