### ISSUE TITLE
Javascript challenges 

### ISSUE THREAD

**Issue by vemba** [wesbos/ama#94]
Hello,

I have started learning HTML5,CSS3,Javascript.It is going all well up till now.I have to test my knowledge on these skills.
Can you post a simple challenges once in a while ?.

**Comment by gethinoakes** [comment]
https://github.com/tastejs/awesome-app-ideas

**Comment by wesbos** [comment]
I've posted a few to Twitter, but I've got a _huge_ bank of them on my computer. So let's just say you are going to like one of my upcoming courses: :)

**Comment by markmur** [comment]
@vemba check out http://codewars.com for improving your JS skills. I've found it really great recently for (1) improving my coding knowledge (2) solving difficult challenges and (3) solving problems faster and more efficiently.
