### ISSUE TITLE
What a cool new gadget you've bought recently?

### ISSUE THREAD

**Issue by smithtimmytim** [wesbos/ama#95]
It can be anything. Us nerdy people are always buying cool little things.

**Comment by wesbos** [comment]
Ohh good question! 

I've been really into [this $6 cheapie fish eye / wide angle lens](http://www.dx.com/p/pho-fwm-6-3-in-1-fish-eye-marco-wide-angle-lens-for-iphone-6-4-7-black-red-361758) - it makes my instagram videos look really nice. The quality is super good and the price means that I've bought a few of them and don't have to baby them. Just throw it into my pocket and use it when I want. 

My wife bought me some [Bose QC25](https://www.amazon.com/gp/product/B00M1NEUKK/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=webo080-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B00M1NEUKK&linkId=8a560e7f48bc27ce51313da98cc782c3)s for christmas over a year ago and they are unbelievable. Super comfortable and they sound great (to me at least - I know some audio nerds will beg to differ).

That's all I can think of right now!
