### ISSUE TITLE
Feedback for an electron app 

### ISSUE THREAD

**Issue by akashnimare** [wesbos/ama#97]
Hey @wesbos 😄 

> 
Focus on building web stuff. It has a very bright future.

Following your advice I'm building more and more stuffs on web 🚀 . I have recently built a desktop app called foco. It's like [noisli](https://www.noisli.com/) but for desktop. It would be awesome if you could try it out and give some valuable feedback.

https://github.com/akashnimare/foco

**Comment by wesbos** [comment]
This looks really cool - I'll try it out next week :) 

Good work on building something!
