### ISSUE TITLE
Family. Work. Courses. BBQ. Etc

### ISSUE THREAD

**Issue by tabishiqbal** [wesbos/ama#98]
It seems like you are making courses. Teaching at HackerYou. Own side projects etc. Wife and kids. How do you manage your time, projects, etc.

**Comment by wesbos** [comment]
Hey! Thanks for the question :) 

I'll start by saying that most of it is an illusion. Almost everything I do is online and public, so you get to see it all. Most people work all day and can't make it public.

That said - I do have a few tips. It all really boils down to making good use of your time. When I'm working, nothing is wasted. When I'm not, I'm with my family.  

I usually work around 9 - 5. Rarely at night unless my wife is away, and never on weekends. 

**1.** I don't commute, I don't have meetings. I don't really go for coffee and I'll often talk down a 'quick skype chat' into a short email. Obviously this isn't a 100% rule, but as a guideline it really helps.  


**2.** [If it's not a hell yes, it's a no](https://www.youtube.com/watch?v=1ehWlVeMrqw) 

Pretty simple yet powerful. Work to cut out things you aren't stoked about. 

If you spread yourself too thin and try to make everyone happy, you don't put out good work and end up letting everyone down. 

**3.** Plan you work, work your plan

I love to jump around to whatever seems fun. When projects are 85% done, they suddenly seem less interesting and get hard to work on.

Over the past few years, I've been learning how to finish things and it's been surprising in how it makes you feel. Once you get one project out the door, the next one suddenly seems so much more achievable. 

**Constantly learning, but these are some things that are working for me right now.**
