### ISSUE TITLE
SublimeCodeIntel

### ISSUE THREAD

**Issue by idd79** [wesbos/ama#99]
Hi Wes, hope everything is going well.

I got your SublimeText book recently and while following your section on SublimeCodeIntel, I was wondering if at the moment installing it using the development branch still makes any difference. I checked the PackageControl site for this plugin and it looks like it is ST3 ready. I have installed it using package control and it is working for me as well (I have ST3), however I'm just wondering if I am missing something out by not installing the development brach.

Thanks in advance.

**Comment by wesbos** [comment]
Hey - I need to update that, looks like its not needed any longer :)
